services:
    behat_test_generator:
        class: BehatTestGenerator\BehatTestGenerator
        public: true

    BehatTestGenerator\Command\TestGeneratorCommand:
        tags:
            - { name: 'console.command', command: 'behat:test:generate' }
